#see https://github.com/marketplace/actions/doxygen-github-pages-deploy-action
name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: DenverCoder1/doxygen-github-pages-action@v1.1.0
        with:
          github_token: ${{ secrets.DOXYGEN_TOKEN }}
          config_file: Doxyfile
